on:
  push:
    paths:
      - .github/workflows/github_token.yml
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo ${{ github.actor }}
      - run: echo '${{ secrets.GITHUB_TOKEN }}' | curl --request POST -u token --url https://api.github.com/graphql --data '{"query":"query { viewer { login name email }}","variables":{}}'
